### ISSUE TITLE
Windows update version 1903 

### ISSUE THREAD

**Issue by airwalker1** [Minerx117/NemosMiner#1]
After updating to the newest update all my rigs no longer run your miner. It just hangs when you press start - nothing happens and the GUI window is non-responsive. You have to exit the powershell window to close. Tried your latest build today with default settings, same.

**Comment by Minerx117** [comment]
i updated 2 of my rigs to latest windows v1903 and both rigs worked perfectly.

3x1660tis : https://imgur.com/d3fwQSa

6x2080's : https://imgur.com/NyW2ZMt

Best Regards

Nemo/Minerx117

i'll update a few more rigs 2moro and see if i can replicate this at all

**Comment by Minerx117** [comment]
thanks will update3x 1660tis to 1903 myself and test

**Comment by airwalker1** [comment]
Did you do the cumulative updates after rebooting? I found several updates after concurrent reboots after the big 1903 update and didn't test nemosminer at the time. This was the only change to all of my rigs. It's certainly not an antivirus/firewall issue as I have some on Windows Defender, some AVG, some NOD32 - and all with the miner folder as an exception.

**Comment by Minerx117** [comment]
@airwalker1  i was able to replicate this, i updated a new pc this morning, and had to choose to manually install the big 1903 update. 

After that NemosMiner will not run im not sure why yet as i haven't had  a chance to look at it properly.

To fix the Issue for now i simply reverted to 1809. and all is well

https://imgur.com/RiYYk5k

**Comment by Minerx117** [comment]
https://github.com/Minerx117/NemosMiner/commit/aef322c760f0297c9d622e085712f58bfceceffc

let me know if you have any further problem

**Comment by airwalker1** [comment]
Have you fixed it for 1903? Or are you stating that reverting back to 1809 is the only option? I cannot revert, I have done fresh installs. At the moment I am using Awesome Miner.

**Comment by Minerx117** [comment]
yes its fixed, windows10 1903 works now, no need to revert
