### ISSUE TITLE
NVSMI/nvml is missing with latest nvidia drivers - Bminer fix

### ISSUE THREAD

**Issue by Minerx117** [Minerx117/NemosMiner#10]
bminer fail to run bminer "cuda error"

caused by nvml.dll not being include in latest drivers

fails to initialize nvml on latest drivers fix

edit: found solution on https://forums.geforce.com/default/topic/1100164/nvml-dll-and-nvsmi-folder-missing/
need to copy nvml.dll from c:\Windows\System32 to C:\Program Files\NVIDIA Corporation\NVSMI (create the folder if missing)

do both Program Files and Program Files (x86)

**Comment by UselessGuru** [comment]
> need to copy nvml.dll from c:\Windows\System32 to C:\Program Files\NVIDIA Corporation\NVSMI (create the folder if missing)

Cannot confirm. The nvml.dll is present in C:\Program Files\NVIDIA Corporation\NVSMI

I installed the lastest 430.86 Nvidia driver like this:
Setup.exe -> Nvidia Graphics Driver [without GeForce Experience] -> Custom (advanced) -> Select Graphics Driver, HD Audio Driver & PhysX System Software

**Comment by Minerx117** [comment]
are you asking a question or just stating something?
