### ISSUE TITLE
Missing Bitcoin icon in the GUI

### ISSUE THREAD

**Issue by borzaka** [Minerx117/NemosMiner#15]
![image](https://user-images.githubusercontent.com/1230402/60711957-3d6a8a00-9f16-11e9-97ad-b5f0f20503ca.png)

![image](https://user-images.githubusercontent.com/1230402/60711991-4ce9d300-9f16-11e9-9a06-6bacbe1fdb8c.png)

Or should I install a specific font for that? Which one?

**Comment by Minerx117** [comment]
all well on my rigs.. be related to 0 balance

**Comment by borzaka** [comment]
OK, I will check back with results when my balance is not 0.

**Comment by Minerx117** [comment]
just downloaded fresh master and checked looks good to me..
https://imgur.com/a/uohBfuX

**Comment by Minerx117** [comment]
just download master and checked looks good to me..

**Comment by borzaka** [comment]
I'am guessing you have a font installed that I don't have. Can you tell which font is the Bitcoin letter using?
Maybe you have Office installed with various extra fonts, but on my dedicated mining rig I don't install any not necessary programs.

**Comment by Minerx117** [comment]
no extra fonts installed, no office or extra programs installed.  all i do when i start a new rig is install windows 7,8,8.1,10 pro fully update it,  then follow these instructions If you have Windows 7, 8, or 8.1, please update PowerShell: update PowerShell

some miners may need 'Visual C++ 2013' if you don't already have it: (install both x86 & x64) Visual C++ Redistributable for Visual Studio 2012/2013

some miners may need 'Visual C++ 2015' if you don't already have it: (install both x86 & x64) Visual C++ Redistributable for Visual Studio 2014/2015

some miners may need 'Visual C++ 2015 update 3' if you don't already have it: (install both x86 & x64) Visual C++ Redistributable for Visual Studio 2015 update 3

running multiple cards its recommended to increase Virtual Memory 64gb is optimal

recommended/optimal Windows Nvidia driver 430.86

Windows10 Standard

Windows10 DCH

Windows7, 8, 8.1 

tried US and Europe versions of windows7,8,8.1,10 both work..

**Comment by Minerx117** [comment]
what version of windows are you trying to run it on?

**Comment by borzaka** [comment]
- Windows 10 Pro - not with the latest updates, but it's not too old.
- Yes, I have installed all the Visual C++ programs
- Yeah, I have 60 gb virtual memory for a 4 card rig
- I have the latest NVIDIA 430.86 driver

Everything works fine with the miners.

My guess, that one of the mining rig optimizer programs removed some unused fonts. Probably one of these:
- [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW)
- [Windows_10_Registry_tweaks_for_mining batch file](https://www.123myit.com/downloads/)
- or other stuff

So, my guess it's not related to NemosMiner.

**Comment by MrPlusGH** [comment]
@borzaka 
This is OS / Font related issue.
Found that the font and symbol is not available on windows server for example.
