### ISSUE TITLE
Plus option devoplment?

### ISSUE THREAD

**Issue by gak45** [Minerx117/NemosMiner#18]
With the public split between yourself and MrPlusGH is the pool plus option going to continue to be refined along a different path than NPLusMiner v5 or is it now DOA in nemosminer? 
Where it is all open source... hoping for the former not latter.

**Comment by Minerx117** [comment]
im not planing on updating plus pool option any time soon, as @MrPlusGH no longer wants me to update from his repo, and i want to Respect that request.. im happy with how it runs for now was only updated not long ago.... your more than welcome to use NplusMiner.  I maintain NemosMiner for myself as i have 30-40k worth of rigs and like to run my own program and have updates when i want them. if other people want to use NemosMiner they are more than welcome to. 

Best Regards
Nemo
