### ISSUE TITLE
Few issues with the new UI

### ISSUE THREAD

**Issue by grantemsley** [Minerx117/NemosMiner#2]
- Pool balances don't show when mining is paused.  Previously it kept tracking/displaying pool balances while paused.
- Some balances are being shown in scientific notation, eg "3.142E-05" instead of decimal.
- Might be personal preference, but I'm not a fan of the way the earnings tracker is colored/styled.  It took me several minutes to even figure out that it's a bar graph.  A white/grey background with black bars might be easier to understand.

**Comment by Minerx117** [comment]
- not worried about balance not being updated while paused.

- only shows scientific notation, eg "3.142E-05" instead of decimal. with very low eg. ( 0 balances )

- may look at changing color in future.. (not atm) after a week or so the graph is very easy to read..
