### ISSUE TITLE
nanominer select device

### ISSUE THREAD

**Issue by squashen** [Minerx117/NemosMiner#20]
Hello.
First of all, thanks for an awesome tool. :)

Now to my problem.
Im runing a rig with 5 1080ti on windows 10.
Lately i have problem with using gpu 0 for mining on some algos and miners, so have start using the option dont use gpu0.
This seems to work pretty well exept for when using nicehashv2 as pool and load their algos. 
I cant se cryptonightR added in the bar with algos, but the tool will anyway try to benchmark it, and when it do it crash the rig immeditly and it restart the computer.
Now i noticed that nemos miner seems to try to start on all 5 gpus even if i check the box "dont use gpu0.   I tried 2 run nanominer outside nemos miner, and it work perfect with eth on all 5 gpu, and it crash on monero with 5gpu, but if i add in the configfile only "device 1,2,3,4" it works perfect.
So the problems see to be that nemosminer put on all 5 gpus in nanominer even if i check the box "dont use gpu0"
Any solution for what to change and where?

Thanks again for an awesome tool.  :)

**Comment by Minerx117** [comment]
delete "nanominer.ps1" from "optionalminers" folder cryptonightR is never profitable on 1080ti's any ways

**Comment by squashen** [comment]
> delete "nanominer.ps1" from "optionalminers" folder cryptonightR is never profitable on 1080ti's any ways

Ahh ok, thank u, that will help me with my problem. :) But maybe fix this for others who have other cards :)

**Comment by Minerx117** [comment]
will do thankyou

**Comment by Minerx117** [comment]
i have disabled nanominer by default and enabled a recompiled version of xmrig cuda 10.1 slightly slower but cuda-device selection works well i can't seem to get nanominer to accept any device commands through cmdline_launcher

**Comment by UselessGuru** [comment]
> i can't seem to get nanominer to accept any device commands through cmdline_launcher

Use a json file:

```

; MPM autogenerated config file
checkForUpdates = false


mport = 0
noLog = true
rigName = Blackbox
watchdog = false
webPort = 4001

[Ethash]
devices = 1
pool1 = asia.ethash-hub.miningpoolhub.com:20605
wallet = UselessGuru.Blackbox
```

The key to get it working is the minerfile / API combo. MPM can create a json from the miner file at runtime.
Please check these two files for a how-to:

https://github.com/UselessGuru/MultiPoolMiner/blob/master/MultiPoolMiner/MinersLegacy/AMD_CPU_NVIDIA-NanoMiner_v1.5.2.ps1
https://github.com/UselessGuru/MultiPoolMiner/blob/master/MultiPoolMiner/APIs/NanoMiner.ps1

And somwhere in core you need this:
https://github.com/UselessGuru/MultiPoolMiner/blob/5a17f78b4220bdbf0be2db97bf732ec9b2b9c070/MultiPoolMiner/MultiPoolMiner.ps1#L827

**Comment by UselessGuru** [comment]
Fixed here: https://github.com/Minerx117/NemosMiner/pull/58

**Comment by Minerx117** [comment]
good things take time thankyou @UselessGuru
