### ISSUE TITLE
MTP mining

### ISSUE THREAD

**Issue by jigoku-shoujo** [Minerx117/NemosMiner#25]
If I disable ccminermtp.ps1 (due to it crashing), the NM doesn't switch to trex.

I couldn't find any error on trex/MTP parameters.

(I have selected zergpoolplus, and I see an if() statement but I cannot understand what it does)

**Comment by Minerx117** [comment]
trex is enabled for nicehash ccminer is enabled for zergpool

if you run only niehash in pools list trex will run for mtp its also only on nicehash old, not nicehashnew

**Comment by Minerx117** [comment]
what version of ccminermtp are you running crashes have been fixed in last few releases, i may have to release v3.8.0.7 today so everyone can update

**Comment by Minerx117** [comment]
if you would still like to use trex for mtp on zergpool you have to edit trex.ps1 in optional miner folder
delete this line: 

If ($Algo -eq "mtp" -and $Pools.($Algo).Host -like "*zergpool*") {return}

save:  

trex will now run on zergpool

**Comment by jigoku-shoujo** [comment]
ccminermtp is version 1.1.26 (https://github.com/zcoinofficial/ccminer/releases/download/1.1.26/ccminer.exe)

Why trex is for nicehash and ccminer for mtp? trex works just fine - unless ccminer giver a bigger hashrate.

Altough in my case, it crashes.

I commented the specific line in trex.ps1 and works fine, thanks/
