### ISSUE TITLE
zpool - Dedal algorithm

### ISSUE THREAD

**Issue by MonaxDK** [Minerx117/NemosMiner#26]
Found this error message
![Clipboard01](https://user-images.githubusercontent.com/29005588/62352580-2917ae00-b511-11e9-8553-26c18d0abbd2.png)

**Comment by Minerx117** [comment]
thanks

**Comment by Minerx117** [comment]
fixed re added trex v0.11.0 last version with dedal support

https://github.com/Minerx117/NemosMiner/archive/master.zip

**Comment by MonaxDK** [comment]
In the new trex.ps1, this algo is disabled, if you turn it on, there will be the same error.

**Comment by Minerx117** [comment]
fixed and done thanks for heads up @MonaxDK 

v3.8.0.7 is released it addresses this issue
