### ISSUE TITLE
ZCL @ MPH

### ISSUE THREAD

**Issue by jigoku-shoujo** [Minerx117/NemosMiner#29]
Can you add ZCL coin at miningpoolhub.com?

I tried making some changes to algorithms.txt but I can't get it to work.

**Comment by Minerx117** [comment]
sure will look into now

**Comment by Minerx117** [comment]
testing atm

**Comment by Minerx117** [comment]
done algud cheers for headsup

**Comment by Minerx117** [comment]
i'll release v3.8.1.1 today with added equihash-zcl support thanks

**Comment by Minerx117** [comment]
sorry for late release
