### ISSUE TITLE
might keep going a little while

### ISSUE THREAD

**Issue by Minerx117** [Minerx117/NemosMiner#31]
https://github.com/MrPlusGH/NPlusMiner

**Comment by grantemsley** [comment]
Well that's sad.

~~At least your version had the decency to share donations with the people who contributed to it.  His as far as I can tell shares with nobody.~~

**Comment by Minerx117** [comment]
atm i have a error on some rigs that i can't seem to fix not effecting mining/or performance but is annoying to see,  

https://imgur.com/a/Pi764AV

if i could get this fixed may carry on maintaining this Repo

**Comment by grantemsley** [comment]
I'll see if I can do anything to track it down.  Should have some time this weekend.

**Comment by MrPlusGH** [comment]
This is sad news Nemo. NemosMiner has been legendary out there.
Not sure about the error you're facing (Haven't installed NemosMiner in a long time) and don't have much time to spend on it these days with the work on NPlusMiner 6.0.
But I'll try to have a look if I can find time.

**Comment by MrPlusGH** [comment]
> 
> 
> Well that's sad.
> 
> At least your version had the decency to share donations with the people who contributed to it. His as far as I can tell shares with nobody.

Not true. I just rechecked.
Nemo has 20% and you 10% of NPlusMiner donations.
I hope I do not have a wrong address in there for you. Please let me know if so:
    http://tiny.cc/r355qy
    
Note: You might have noticed that you and Nemo got excluded from this list at times lately has I changed it for some tests on NPlusMiner 6.0.
You even have the ability to be more precise as to how you want to direct your part in 6.0 now using "PoolsConfURL" if you want to. 
Just give me the URL to use so I update.

**Comment by grantemsley** [comment]
@MrPlusGH my sincere appologies then.  I must have checked while you were testing things.  Thanks for clearing that up.

**Comment by Minerx117** [comment]
i have managed to track it down and fix problem, i had some time over the weekend.. all is well happy days
