### ISSUE TITLE
Release Candidate20 for upcoming Version 4 ready

### ISSUE THREAD

**Issue by UselessGuru** [Minerx117/NemosMiner#71]
https://github.com/Minerx117/NemosMiner/releases/tag/v4.0.0.20(RC20)
For a list of changes in this version see https://github.com/Minerx117/NemosMiner/blob/testing/ChangeLog.txt

**Comment by UselessGuru** [comment]
@99RedBalloonsgoby 

The original MultiPoolMiner project is dead. Feel free to use NemosMiner.

**Comment by 99RedBalloonsgoby** [comment]
Thank you, where might I go to get help to get a lil help? I'm almost there
save I get 'No Miners!' in the bat.exe screen. Excluded folder in Windows
Security, same results from different web browsers (chrome/brave). I know I
may have missed a small step somewhere and if you can point me to a
troubleshooting guide it'd be a great help, I really want to move over to
Nemos and stay up to date.  TIA Pete.

**Comment by UselessGuru** [comment]
Did you install NemosMiner to a new directory?
Did you complete the config (e.g. wallet / user name, pools?
Can you post the contents of your config file (remove confidential info first)?

**Comment by UselessGuru** [comment]
@nzebrian

The original MultiPoolMiner project is dead. Feel free to use NemosMiner, it is based on the original MultiPoolMiner code, but has lots of new features. I recommend you use the 3.9.9.X code.

**Comment by UselessGuru** [comment]
v4.0.0.28 is now master
