### ISSUE TITLE
Getting Zero hashrate for Ethminer .19.0r4

### ISSUE THREAD

**Issue by emike09** [Minerx117/NemosMiner#72]
Hello,
I'm getting 0 hashrate when using Ethminer, not sure why or how to start troubleshooting. Using an RTX 3080 FE. Here is the console output:
```
m 16:14:45 <unknown> 0:00 A0 0.00 h -
 i 16:14:47 <unknown> New API session from 127.0.0.1:62080
 i 16:14:47 <unknown> API : Method miner_getstat1 requested
 i 16:14:50 <unknown> New API session from 127.0.0.1:62083
 i 16:14:50 <unknown> API : Method miner_getstat1 requested
 m 16:14:50 <unknown> 0:01 A0 0.00 h -
 i 16:14:52 <unknown> New API session from 127.0.0.1:62086
 i 16:14:52 <unknown> API : Method miner_getstat1 requested
 m 16:14:55 <unknown> 0:01 A0 0.00 h -
```
Running Windows 10 2004. Any tips into what to look into?

**Comment by UselessGuru** [comment]
EthMiner is not well maintained and is currently not compatible with latest Nvidia driver.
Just let the benchmark fail three times, NemosMiner will then remove EthMiner from the list of available miners.
PhoenixMiner & TT-Miner are much faster anyway for EthHash mining.


BTW: I recommend you try the latest Beta version:
https://github.com/Minerx117/NemosMiner/issues/71

**Comment by emike09** [comment]
Makes sense, I read elsewhere that the latest nVidia drivers caused problems. Had to enable optional miners to get tt-miner and phoenixminer. Beta seems to be running great!

**Comment by Minerx117** [comment]
ethminer needs to be compiled with cuda 11.1+ to work with 30 series i'll look into today and try recompile it so it works

**Comment by emike09** [comment]
You guys are great! I'm not sure how NemosMiner isn't the most popular Windows mining platform, been using it since MPM was first released then forked.

**Comment by Minerx117** [comment]
please try Ethminer .19.0r5 compiled with cuda 11.1
https://github.com/Minerx117/NemosMiner/commit/2c40bbf9482a4fed6d1202b730cd4bfd6dd59f04
https://github.com/Minerx117/NemosMiner/commit/51f8894b9a84d00153067841ee7daf5dc36849df

**Comment by emike09** [comment]
Seems to be working, and at a slightly better hashrate too it seems. Thanks!

**Comment by UselessGuru** [comment]
@emike09 
Are you running Beta 3.9.9.x? Any feedback is very welcome.

**Comment by emike09** [comment]
I am. 3.9.9.8 b2. I've actually been running from the testing branch the last few weeks since it seems to be getting updated frequently. I like the web interface more than the PS interface in 3.8.1.3. At first I was confused as to how to turn off CPU mining since it wasn't under Edit Config, but found I could disable CPU mining under Devices when I wanted to. 

It seems there is a massive amount of time spent mining to donation accounts, in particular aaronsace and grantemsley. My donation per day is the standard 13 minutes, but far more than that is being spent mining to other accounts instead of my own. 
See [Log](https://docs.google.com/spreadsheets/d/1Wz8_0_J267CTU0s1_ONjDBANZjd9Dca3QdBsvlQlVcg/edit?usp=sharing).

Also curious if NemosMiner_PWSH7.bat provides any benefit over that standard NemosMiner.bat launcher.

**Comment by UselessGuru** [comment]
@emike09 
There is seriously something wrong with the donation routine. 👎 
Do you have the part of the nemos log (\Log\NemosMiner_YYYY_mm_dd) available from where the problem started?

**Comment by UselessGuru** [comment]
> Also curious if NemosMiner_PWSH7.bat provides any benefit

Not in terms of profit optimization.
But I see a lot of potential by moving to PWSH 7 because of it's new features.

**Comment by UselessGuru** [comment]
@emike09 

Please try https://github.com/Minerx117/NemosMiner/commit/4d7bbb97098dcf1f0e7a8a5e44359886718d9946
This should fix the donation mining bug. Thank you for your support!

**Comment by UselessGuru** [comment]
@emike09 

> At first I was confused as to how to turn off CPU mining

~~I will add device config to the 'normal' config editor~~

Added in https://github.com/Minerx117/NemosMiner/commit/3dceb4fa5cc34f11b6a7ee06e55bfa5dc2edd7f6

**Comment by emike09** [comment]
What are the chances of having a user selectable CPU priority for CPU mining? I've noticed most miners are set to Below Normal but I'd like to have them set to Low by default without having to do so in task manager. On that note, normal system responsiveness doesn't seem to improve much by moving to low. Probably CPU cache related? Trying to mine both CPU and GPU on the system I use for work at home.

**Comment by emike09** [comment]
Apps been crashing a lot. Snake tail and the cmdline output stay active, but the PS runtime quits as well as miners. 
[Logs_2.zip](https://github.com/Minerx117/NemosMiner/files/5727950/Logs_2.zip)

**Comment by UselessGuru** [comment]
> What are the chances of having a user selectable CPU priority for CPU mining? 

Done:

![image](https://user-images.githubusercontent.com/30080938/103155318-08ec2d00-479f-11eb-915c-ecea69daaddd.png)

https://github.com/Minerx117/NemosMiner/commit/7eb5444ca1519f367a62e6dc41f39c65678d53bc

**Comment by UselessGuru** [comment]
> Apps been crashing a lot. 

What do you mean by 'Apps'?

For more debug information you can enable powershell transcripts:

Set `  "Transcript": true,` in the config file and restart NM. It will create extra 'transcript-*' files in the log folder.

**Comment by emike09** [comment]
This is awesome, thanks for the changes to CPU and GPU miner priorities. 

Nemosminer seems stable again, it may have been a specific miner or something else on my computer that was causing crashes, but I think we're good for stability.

**Comment by emike09** [comment]
What about an option to define the number of CPU treads to mine on? I have 8 cores, 16 threads, but sometimes might just want to mine on 6 cores/12 threads and leave the rest for the OS and other applications. I think CPU cache will still slow down the remaining threads but it'd be nice to have the option.

**Comment by UselessGuru** [comment]
> What about an option to define the number of CPU treads to mine on?

CPU miners should never run on all cores. 1 one core is usually reserved.
I this not the case?

An option to exclude a number of Cores / Threads would probably make more sense (Default 1 Core).

Personally I advise to NOT USE CPU mining. It is simply not worth it, and can have adverse side effects.

**Comment by emike09** [comment]
Yeah probably shouldn't, but I have so much CPU to spare, more than I specified. What are the options for auto-updating either the master or test branch so we don't have to do so daily?

**Comment by UselessGuru** [comment]
> What are the options for auto-updating

Latest version 3.9.9.12 has (experimental) auto update.
https://github.com/Minerx117/NemosMiner/releases/tag/v3.9.9.12

**Comment by UselessGuru** [comment]
@emike09 

Did you try the latest builds (autoupdate)?

**Comment by emike09** [comment]
I did, though I noticed the web gui isn't opening. 

2021-01-06 11:59:15 VERBOSE: Initializing API & Web GUI on 'http://localhost:3999'
2021-01-06 11:59:21 ERROR: Error starting Web GUI and API on port 3999.

**Comment by emike09** [comment]
I take that back, auto update and web gui works just fine on my other two computers. Deleting the folder, rebooting, and manually re-installing on my 3rd computer let the web gui pull up just fine.

**Comment by emike09** [comment]
For some reason, I'm mining to Zergpool even though I only have MPH selected as my pool. Might just be part of benchmarking?

![image](https://user-images.githubusercontent.com/9699530/103856995-dbdb2c80-5072-11eb-832c-2bff439d6fca.png)

**Comment by UselessGuru** [comment]
> Might just be part of benchmarking?

No, benchmarking just uses the configured algorithms.
But the donation run uses ALL pools. You should find a message like 
`Donation run: Mining for '...' for the next ...`
 in your logs.
Donation kicks in once per day @ random time.

Edit: I'll improve the donation message so that it states that NM will use all pools while donating.

**Comment by UselessGuru** [comment]
@emike09 

Can this be closed? Pls close if so.
Please create a new issue for each problem. Thank you.

**Comment by emike09** [comment]
Of course. Thank you.
