### ISSUE TITLE
ttminer continuously fails at benchmark, but keeps trying it

### ISSUE THREAD

**Issue by misterbrucewayne** [Minerx117/NemosMiner#73]
I have a few ttminer attempts that keep trying to benchmark even though they get some CUDA error and it says GPUs are disabled (it flashes too fast and is slightly different every time so I can't read it). One of them finally failed after 48 starts, but the other one is at 100+ and counting.

![Screenshot 2021-01-08 111431](https://user-images.githubusercontent.com/35897270/104050000-252a9980-51a3-11eb-9c4f-c72d2e063ba8.png)

**Comment by misterbrucewayne** [comment]
I'm trying 3.9.9.12 now and will report back if there are still issues

**Comment by UselessGuru** [comment]
> One of them finally failed after 48 starts, but the other one is at 100+ and counting.

Can you please update the log?
It should only benchmark 3 times per algo.

**Comment by misterbrucewayne** [comment]
@UselessGuru - this doesn't appear to be an issue once I updated to 3.9.9.12 (and 3.9.9.13 today). I can still pull the old log file if you want it though, just not sure exactly what you need.

Side question - what's recommended when updating versions? Is it best to just start from scratch with config and benchmarking, or just copy in certain files that updated?

**Comment by UselessGuru** [comment]
> what's recommended when updating versions?

Just enable 'Auto update'. There are no special considerations since you are on the 3.9.9x branch.
NemosMiner automatically updates all relevant files. It will also benchmark new miners and miner versions.
