### ISSUE TITLE
config.json file missing in 3.9.9.17 and running issues

### ISSUE THREAD

**Issue by colbzc** [Minerx117/NemosMiner#75]
I tried running the current beta as of 1/26. Went through the steps of updating the config file in the web app, hit save, and a blank window pops up. When I hit start mining, another blank window pops up.
Upon further inspection, noticed it was telling me the config file name was under config/config.json. Turns out no such file exists.
My good friend, I'll call him my brother, gave me a copy of the config file he had from a working previous 3.9.9.17 build, and I created my own config.json.
after a fresh unzip and adding that missing config, running the NewmosMiner batch file skipped over the first time setup, and recognized the config, landing me on the dashboard, with a greyed out 'start miner' and selectable stop/pause miner.
If I try to navigate away from the dashboard, it says the page can't be reached.

**Comment by UselessGuru** [comment]
I cannot reproduce your issue. I did:

1. Download the zip file
https://github.com/Minerx117/NemosMiner/archive/v3.9.9.17.zip
2. Unzip to a new folder
3. Start NemosMiner
    -> purple message 'No valid configuration file found.' That is to be expected.
4. Browser window opens and displays the welcome message
5. Entered my BTC address in the 'Bitcoin wallet address' field
6. Set the worker name
7. Unticked 'MPH' pool (cause I did not enter MPH Username/API)
8. Apply config
9. 'Start mining' button turns green -> Click -> Mining starts.

You need Powershell 7.x installed. I run version  7.1.1 which can be downloaded from here:
https://github.com/PowerShell/powershell/releases

**Comment by colbzc** [comment]
@UselessGuru you are right! I had 7.1.1 installed, but looks like I had failed to uninstall the previous 6.x version, and the miner was grabbing that to attempt to run things.

**Comment by UselessGuru** [comment]
Thank you for reporting back.
I've added a pwsh version check to avoid such issues in the future.
