### ISSUE TITLE
Visual C++ 2015-2019 Redistributable (X64) 14.28.29325 Install loop

### ISSUE THREAD

**Issue by colbzc** [Minerx117/NemosMiner#76]
I've had issues since starting the new 3.9.9.17 where it constantly wants me to install Visual C++ 2015-2019 Redistributable (X64). I already had it installed, so it showed options to repair or uninstall. I tried uninstalling, restarting, running, installing, restarting, and running NemosMiner again, but it's still telling me to install. Attached is the log of what's going on. If I just hit close, it says the downloader has all tasks complete.
I've also run your all-in-one setup from 2019 to cover all my bases, but no luck.

![1](https://user-images.githubusercontent.com/35206627/106219190-1f1e4c00-6196-11eb-819e-9ce941a5c577.JPG)

**Comment by UselessGuru** [comment]
For some reason $env:SystemRoot\System32\VCRUNTIME140_1.dll cannot be found, even after installing the VC redistributable.

More info here:
https://www.howto-connect.com/fix-vcruntime140_1-dll-was-not-found-windows-10/

**Comment by colbzc** [comment]
As an FYI, I followed all those steps and could not resolve the issue. This issue was the last straw in a decision to do a fresh install of Windows, and that seemed to resolve it unfortunately. Hopefully nobody else has this issue.
