### ISSUE TITLE
Gminer restarting every few minutes

### ISSUE THREAD

**Issue by emike09** [Minerx117/NemosMiner#77]
For some reason, GMiner keeps restarting every 2-3 minutes. Not sure why. Temps are good, and I have my doubts it's to mine for donation, but if it is, it's way too frequent. Benchmarking phase is complete. It'd be nice if the miner continued mining once it was determined to be the best thing to mine. 
[Logs.zip](https://github.com/Minerx117/NemosMiner/files/5900646/Logs.zip)
Also, is there a better way of keeping the miner window minimized instead of taking foreground every time it launches? I mine in the background while I'm using my main desktop, and having a window pop up every time the miner restarts is kind of annoying. I have "Run miner as hidden background task" selected.

**Comment by UselessGuru** [comment]
> For some reason, GMiner keeps restarting every 2-3 minutes.

3.9.9.17 has an issue with watchdog timers. What if you disable the watchdog?

> Also, is there a better way of keeping the miner window minimized instead of taking foreground every time it launches?

Yes, untick this:
![image](https://user-images.githubusercontent.com/30080938/106420367-c4694680-645a-11eb-84ab-f9ce7161e0b8.png)
