### ISSUE TITLE
Dashboard and cmd window earnings are only reporting Zergpool despite not checking that in the config

### ISSUE THREAD

**Issue by colbzc** [Minerx117/NemosMiner#78]
Nothing too lengthy to describe, but in my dashboard, under balances, only zergpool is listed, even though that's not checked in my config. In fact, I only have MPH checked for the last few weeks, and my MPH balance does not show up.
this same issue is reflected in the cmd prompt window. The earnings numbers are probably accurate for what was mined during a benchmark, but I'm making a few bucks a day on each computer. And that is accurately reflected in the top banner of the gui.

I don't know if this is related or not, but sometimes I come back after pausing mining, to find my config in the web gui blank, minus my MPH username. But when I look at the actual config file on my desktop, it's all in there...

<img width="1397" alt="Screenshot 2021-02-09 111143" src="https://user-images.githubusercontent.com/35206627/107408030-a1c4d680-6ac7-11eb-8ca3-191cc4bf9dc0.png">
<img width="353" alt="Screenshot 2021-02-09 111118" src="https://user-images.githubusercontent.com/35206627/107408038-a38e9a00-6ac7-11eb-85af-7bf2bd081840.png">

**Comment by UselessGuru** [comment]
What version is that?

**Comment by colbzc** [comment]
Sorry, this is on v3.9.9.17

**Comment by UselessGuru** [comment]
> to find my config in the web gui blank, minus my MPH username.

Is the config in 'Running Config' complete? I have seen timing issues that corrupts the data in the config editor.
I have added a fix for this in the upcoming 3.9.9.18

I cannot think of a reason for your problem.
Try renaming the Logs folder. You will lose hostorical data (earnings stats for 30 days) and payday preddiction will start fresh.

**Comment by colbzc** [comment]
my running config looks complete. But next time it shows up blank, I'll double check.

renamed the logs folder, and will report back any updates.

**Comment by colbzc** [comment]
Renaming the logs folder did create a new logs folder upon relaunch, but I am still only showing Zergpool. I tried switching off MPH and am only on Nicehash pool right now.

**Comment by UselessGuru** [comment]
@colbzc 

Can you post the contents of your config file (remove confidential info first)?

**Comment by colbzc** [comment]
{
  "Algorithm": "",
  "AllowedBadShareRatio": 0.1,
  "APILogfile": "",
  "APIPort": 3999,
  "AutoStart": true,
  "AutoUpdate": true,
  "BalancesTrackerLog": false,
  "BalancesTrackerPollInterval": 15,
  "CalculatePowerCost": false,
  "ConfigFileVersion": "3.9.9.17",
  "CPUMinerProcessPriority": 1,
  "Currency": [
    "USD",
    "BTC"
  ],
  "Delay": 1,
  "DisableDualAlgoMining": false,
  "DisableMinerFee": false,
  "DisableMinersWithFee": false,
  "DisableSingleAlgoMining": false,
  "Donate": 13,
  "EstimateCorrection": false,
  "ExcludeDeviceName": [
    "CPU#00"
  ],
  "ExcludeMinerName": "",
  "GPUMinerProcessPriority": 1,
  "IdlePowerUsageW": 60,
  "IdleSec": 120,
  "IgnoreMinerFee": false,
  "IgnorePoolFee": false,
  "IgnorePowerCost": true,
  "IncludeLegacyMiners": true,
  "IncludeOptionalMiners": true,
  "IncludeRegularMiners": true,
  "Interval": 240,
  "LogToFile": [
    "Info",
    "Warn",
    "Error",
    "Verbose",
    "Debug"
  ],
  "LogToScreen": [
    "Info",
    "Warn",
    "Error",
    "Verbose",
    "Debug"
  ],
  "MarginOfError": 0,
  "MinAccuracy": 0.5,
  "MinDataSamples": 20,
  "MinDataSamplesAlgoMultiplier": {
    "X25r": 3
  },
  "MinerInstancePerDeviceModel": false,
  "MinerSet": 1,
  "MineWhenIdle": false,
  "MinWorker": 10,
  "MonitoringServer": "https://nemosminer.com",
  "MonitoringUser": "xx",
  "MPHAPIKey": "xx",
  "MPHUserName": "colbzc",
  "NiceHashAPIKey": "xx",
  "NiceHashAPISecret": "xx",
  "NiceHashOrganizationId": "",
  "NiceHashWallet": "xx",
  "NiceHashWalletIsInternal": false,
  "OpenFirewallPorts": true,
  "PayoutCurrency": "BTC",
  "PoolName": [
    "NiceHash"
  ],
  "PoolTimeout": 30,
  "PowerPricekWh": {
    "00:00": 0
  },
  "PricePenaltyFactor": 1,
  "ProfitabilityThreshold": -99999,
  "ProHashingAPIKey": "",
  "ProHashingUserName": "",
  "Proxy": "",
  "Region": "US",
  "ReportToServer": true,
  "RunningMinerGainPct": 5,
  "ShowAccuracy": true,
  "ShowAllMiners": false,
  "ShowEarning": false,
  "ShowEarningBias": false,
  "ShowMinerFee": true,
  "ShowMinerWindows": "hidden",
  "ShowMinerWindowsNormalWhenBenchmarking": false,
  "ShowPoolBalances": true,
  "ShowPoolFee": true,
  "ShowPowerCost": false,
  "ShowPowerUsage": false,
  "ShowProfit": false,
  "ShowProfitBias": false,
  "ShowWorkerStatus": true,
  "SnakeTailConfig": ".\\Utils\\NemosMiner_LogReader.xml",
  "SnakeTailExe": ".\\Utils\\SnakeTail.exe",
  "SSL": false,
  "StartGUIMinimized": true,
  "StartPaused": false,
  "SyncWindow": 5,
  "Transcript": false,
  "UIStyle": "Light",
  "UnrealPoolPriceFactor": 2,
  "Wallet": "xx",
  "WarmupTime": 30,
  "Watchdog": true,
  "WatchdogCount": null,
  "WebGUI": true,
  "WorkerName": "xx"
}

**Comment by UselessGuru** [comment]
@colbzc 

Your config looks ok.
I assume that you have mined at Zergpool, either with NM another mining program. That is why you see a ZergPool balance.
NM only shows a balance if there is some unpaid balance.

When you mine with NiceHash with a internal wallet, then you need these all of these 4 confing items

"NiceHashAPIKey": "xx",
"NiceHashAPISecret": "xx",
"NiceHashOrganizationId": "**xx**",
"NiceHashWalletIsInternal": true,

When you mine to an external wallet (not recemmended by NH) then you just define the wallet
"NiceHashWalletIsInternal": true,
"NiceHashWallet": "xx", (only if different from std. wallet, otherwise leave empty).

For NiceHash it will take a while until balance data will show.

> my MPH balance does not show up.

Please confirm your mph api key is correct - this does work. Note that MPHAPIKey  is case sensitive!

**Comment by colbzc** [comment]
I haven't voluntarily used Zergpool ever. The only time I think it could have mined there was either benchmarking or donation periods of mining?

Noted on the required organization ID. It was separate from API settings in Nicehash, and I'm not an business with a VAT number or anything that it requires to set up an organization, so I didn't add that.

For the MPH balance it looks like the API Key is all lower case in both MPH and in my config.

**Comment by UselessGuru** [comment]
> like the API Key is all lower case 

MPH: Did you set auto exchange coin to Bitcoin? 
3.9.9.17 does not support other coins. I am working on 3.9.9.18 that will support other coins.
You can also contact me in discord if you want me to do more research.

**Comment by UselessGuru** [comment]
@colbzc 

Any news?

**Comment by colbzc** [comment]
I do indeed have my autoexchange on MPH set to Bitcoin.
Once I ran it again this morning and it updated to 3.9.9.18 I am now seeing pool balances again! Though Zergpool still shows up, at least I can see the others now!

**Comment by UselessGuru** [comment]
> I am now seeing pool balances again!

Thank you for reporting back.
I assume that some balance data files were corrupted. 3.9.9.18 removed these.

> Though Zergpool still shows up, at least I can see the others now!

NemosMiner will always report the balances from ALL supprted pools where there are pending balances.
You must have mined @ zergpool at some stage - this must not have been with NemosMiner.
