### ISSUE TITLE
Latest update fails to start any miners

### ISSUE THREAD

**Issue by grantemsley** [Minerx117/NemosMiner#84]
After updating it just goes in an infinite loop of starting new cycles, loading pool and miner date, then starting a new cycle.

In errors log I see:

```
Compare-Object: c:\nemos\Includes\Core.ps1:892
Line |
 892 |  …                        If (Compare-Object $MinerFirewallRules @($Mine …
     |                                              ~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'ReferenceObject' because it is null.
```

**Comment by UselessGuru** [comment]
Please try https://github.com/Minerx117/NemosMiner/releases/tag/v4.0.2.2

Note: Error has been around for much longer... but did not come up until new firewall ports needed opening.
