### ISSUE TITLE
Autoupdate backups take too long/take too much disk space

### ISSUE THREAD

**Issue by grantemsley** [Minerx117/NemosMiner#85]
Backups are great, but lately the auto backups are >8GB each, and take quite awhile to run. Is there an option somewhere to skip the backups when automatically updating?

Better yet would be cleaning up old miners after the update is done. The majority of that 8GB is the verthash.dat file for multiple older versions of SRBMinerMulti. Having it automatically clean up old versions would help a lot. Or just having autobackup skip some known huge and useless files that some of the miners generate?

**Comment by grantemsley** [comment]
Wow looking through the recent commits I see you *just* excluded verthash.dat from the backups. Great minds think alike I guess? :)

**Comment by UselessGuru** [comment]
>  Great minds think alike I guess? :)

Seems so :-)

**Comment by grantemsley** [comment]
Still, I wouldn't mind an option to disable the backups entirely. I already have full system backups I can restore from if I need to.

**Comment by UselessGuru** [comment]
> Still, I wouldn't mind an option to disable the backups entirely

Good idea!
I'll also add removing old miners binaries.

Edit:  Both implemented in https://github.com/Minerx117/NemosMiner/commit/4776bef4a0c91d0dc1c78e4ffc5855199d1d6f21. Changes will also be in the next release.
