### ISSUE TITLE
Can't install nemosminer

### ISSUE THREAD

**Issue by Mackandal1** [Minerx117/NemosMiner#86]
I followed all the step and download vcr, pws 7.25 and so on. But the batch splashed and closed. Thanks for help in advance.

**Comment by UselessGuru** [comment]
Sounds like NemosMiner cannot find PWSH.exe.

What happens when you start a cmd window and then enter 'pwsh' at the prompt?
If it says something like 'pwsh is not recognized as an internal or external command' then PWSH ist not installed properly or the path variable ist not set properly. This might give you an idea: https://confluence.atlassian.com/bamkb/powershell-is-not-recognized-as-an-internal-or-external-command-1095246216.html (this is not about NemosMiner but the solution is the same except you will need to set the path for PWSH.exe and not PowerShell.exe)

**Comment by Mackandal1** [comment]
Thanks for rapid response. I found the solution. I had to reinstall vcr.
And Bingo!

Le lun. 25 juill. 2022, 12 h 49, Useless Guru ***@***.***> a
écrit :

**Comment by Mackandal1** [comment]
Also, nemos batch won't if i try to launch as administrator.

Le lun. 25 juill. 2022, 12 h 51, Ernst Jean Poitevien ***@***.***> a
écrit :

**Comment by UselessGuru** [comment]
> Also, nemos batch won't if i try to launch as administrator.

Same reason. You need to set the path to PWSH also for the Admin account.
It is best to add the PWSH path to the system path.

**Comment by Mackandal1** [comment]
Ok, thanks.

Le lun. 25 juill. 2022, 12 h 54, Useless Guru ***@***.***> a
écrit :

**Comment by UselessGuru** [comment]
Does it work now (running as admin)?

BTW: Where did you find the link to this software?

**Comment by Mackandal1** [comment]
No doesn't work. Is that you call "system path" : put the path to
environnement variables ? If it's so, i did. Otherwise, what it is or what
else I should ?

Le lun. 25 juill. 2022, 15 h 12, Useless Guru ***@***.***> a
écrit :

**Comment by UselessGuru** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/30080938/180868408-fc9a1934-58b3-4977-b1bf-f97c0255daee.png">

<img width="443" alt="image" src="https://user-images.githubusercontent.com/30080938/180868745-f0d04072-3ba8-4910-8afd-3f1f3ac8c253.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/30080938/180868152-f82ad7ee-321f-4dd4-af2b-a4e44650ab5d.png">

**Comment by Mackandal1** [comment]
I follow the step but nothing works. 😞

Le lun. 25 juill. 2022, 16 h 31, Useless Guru ***@***.***> a
écrit :

**Comment by UselessGuru** [comment]
What happens if you open a CMD window **as administrator** and then type pwsh?

**Comment by UselessGuru** [comment]
Also try this (this is what NemosMiner.bat file does) **in the NemosMiner directory**:

`PWSH -executionpolicy bypass -windowstyle maximized -command ".\NemosMiner.ps1 -ConfigFile '.\Config\config.json'"`

Once as admin, one as normal user.
What error messages do you get?

**Comment by Mackandal1** [comment]
when I type pwsh as admin I this :

PS C:\Windows\System32> pwsh
PowerShell 7.2.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Windows\System32>

when I type : PWSH -executionpolicy bypass -windowstyle maximized -command
".\NemosMiner.ps1 -ConfigFile '.\Config\config.json

I have this :

PS C:\Windows\System32> PWSH -executionpolicy bypass -windowstyle maximized
-command ".\NemosMiner.ps1 -ConfigFile '.\Config\config.json
>>


Like I told you, it works as normal user






;
*Ernst Jean Poitevien*

*Veritas veritatis et omnia veritas*

**Comment by UselessGuru** [comment]
> PS C:\Windows\System32>
when I type : PWSH -executionpolicy bypass -windowstyle maximized -command
".\NemosMiner.ps1 -ConfigFile '.\Config\config.json

In above message you are not in the NemosMiner directory. Like this PWSH cannot find the script to run.

You prompt must be something like 'PS C:\Users\\[Username]\Desktop\NemosMiner>'.

**Comment by Mackandal1** [comment]
When i execute this command :

PWSH -executionpolicy bypass -windowstyle maximized -command
".\NemosMiner.ps1 -ConfigFile '.\Config\config.json'"
it works.

Thank you very much for patience.

*Ernst Jean Poitevien*

*Veritas veritatis et omnia veritas*

**Comment by UselessGuru** [comment]
> Thank you very much for patience.

You're welcome.
