### ISSUE TITLE
Failure to use GPU count over 10

### ISSUE THREAD

**Issue by airwalker1** [Minerx117/NemosMiner#88]
I have a rig that has 11 gpus and only 10 will work - at least with MiniZ. I will test others. Anyway, the issue is with the count variable converting to the following output for the command line : " -cd 0 1 2 3 4 5 6 7 8 9 a".

I believe this is the conflicting argument from the miniz.ps1 : -cd $(($AvailableMiner_Devices.$DeviceEnumerator | Sort-Object -Unique | ForEach-Object { '{0:x}' -f $_ }) -join ' ')" -replace "\s+", " ").trim()

**Comment by airwalker1** [comment]
I believe I have corrected it by adding a double digit padding operator. From original '{0:x}' to '{0:d2}' . In theory, should work for up to 99 miners.

**Comment by UselessGuru** [comment]
Thank you for the input! Unfortunately I do not have that many GPUs to test.

I will update the miner code. The fix will be in the next release.

Are there other miners with the same problem?

**Comment by airwalker1** [comment]
Appears to have the same code in all miners.  Easy enough to fix with a find & replace edit. I've been mining successfully without error for several hours now.

**Comment by UselessGuru** [comment]
> Appears to have the same code in all miners

True, but some miners require device IDs in hex (hence that code).
