### ISSUE TITLE
Octopus Algo AMD Support? 

### ISSUE THREAD

**Issue by Minerx117** [Minerx117/NemosMiner#90]
can you add Octopus Algo Support for RX5xxxx and RX6xxxx series GPU's

nanominer has implemented a kernel for RX5 and RX6 series cards..

[nanominer v3.6.8](https://github.com/nanopool/nanominer/releases/tag/v3.6.8)
Added Conflux (Octopus algorithm) for AMD RDNA GPUs (RX 5xxx and RX6xxx).
Fixed nanominer crashes.
Approximate average performance (without OC):
RX 6800XT: 22.9 MH/s
RX 6700XT: 13.7 MH/s
RX 6600: 9 MH/s
RX 5700XT: 13.9 MH/s

**Comment by UselessGuru** [comment]
Please try
https://github.com/Minerx117/NemosMiner/commit/644f30e08a0b545321dae99eb9b76bcfa5d4d6c5
https://github.com/Minerx117/NemosMiner/commit/e58761c8db976645ff59f365d932469ee8004320
You need them both!

**Comment by Minerx117** [comment]
yeh that works
