### ISSUE TITLE
MiningPoolHub prices seem to be at least twice what it should be

### ISSUE THREAD

**Issue by Minerx117** [Minerx117/NemosMiner#91]
also i do not have MiningPool Hub selected in config only have zergpool and nicehash selected by its still mining to Mining Pool Hub can only get it to stop by deleting MininpoolHub.ps1 in pools folder

https://ibb.co/3S4q2M2

**Comment by UselessGuru** [comment]
Donation run?
Please PM to my Discord account (UselessGuru) a log extract from the time this happended as well as the config used.

**Comment by Minerx117** [comment]
think it was donation run yes.. what about the price?

**Comment by UselessGuru** [comment]
>  what about the price?

Nothing we can do about. The price data comes from the pool API.
You can set a custom EarningsAdjustmentFactor in 'Config\PoolsConfig.json' like this:

```
  "MiningDutch": {
    "EarningsAdjustmentFactor": 0.8,
    "ExcludeRegion": []
  },
  "MiningPoolHub": {
    "EarningsAdjustmentFactor": 0.8,
    "ExcludeRegion": [
      "Europe"
    ],
    "PayoutThreshold": {
      "ETH": 0.25,
      "mBTC": 50
    }
  },
  "NiceHash": {
    "EarningsAdjustmentFactor": 0.9
  },
  "ZergPool": {},
  "ZPool": {}
}
```

Edit: Config\Pool**s**Config.json

**Comment by Minerx117** [comment]
ok
