### ISSUE TITLE
sha512256d Radiant RXD 

### ISSUE THREAD

**Issue by Minerx117** [Minerx117/NemosMiner#92]
https://zpool.ca/algo/sha512256d

https://github.com/xiaolin1579/radiator/releases/tag/v1.0.0

**Comment by UselessGuru** [comment]
Radiand currently has no price information @ Zpool.
Pools without price information are not supported by Nemosminer
When pool adds price information then the algo will autmagically become available with SRBMiner-v1.0.9 & and Wildrig-v0.32.4.

I will see how we can add xiaolin miner.

**Comment by UselessGuru** [comment]
Xiaolin Radiator miner will be in next update.
https://github.com/Minerx117/NemosMiner/commit/6b863c5188b0c5dbd7bd9bc22de5660ad2f357c4

**Comment by Minerx117** [comment]
thankyou
