### ISSUE TITLE
nemosminer.com domain expired

### ISSUE THREAD

**Issue by grantemsley** [Minerx117/NemosMiner#93]
Rig monitoring is no longer working because the domain has expired.

I'm not sure if nemos lost access to that as well when they lost the original github account for this. If they still have access they need to renew it. Otherwise might be time to rename this miner and pick a new domain?

**Comment by Minerx117** [comment]
i have renewed for another 12months sorry it was down for 12-14 hours..

**Comment by grantemsley** [comment]
Yay! You're certainly not the first to forget to renew a domain, and you wont' be the last. Glad you got it sorted out easily!
