### ISSUE TITLE
cant seem to get srbminer to run at all on my cpus..

### ISSUE THREAD

**Issue by Minerx117** [Minerx117/NemosMiner#94]

**Comment by UselessGuru** [comment]
Sorry, support is limited the next few weeks (holidays) ;-)

**Comment by UselessGuru** [comment]
Try this:

[SRBMinerMulti-v1.1.0.zip](https://github.com/Minerx117/NemosMiner/files/9900479/SRBMinerMulti-v1.1.0.zip)

**Comment by Minerx117** [comment]
thank you that fixed it : ) best regards
