### ISSUE TITLE
BTC wallet need to be less than 34 char!!

### ISSUE THREAD

**Issue by arminmacx** [Minerx117/NemosMiner#95]
Hi,

I tried to add my BTC wallet but each time it says wallet address need to be less than 34 characters. why its not support new wallets when other apps can use them?

**Comment by UselessGuru** [comment]
I am not aware that BTC wallets can be longer. I will check.

As a workaround you can edit the config file manually and set a longer value.

Edit: Fixed in https://github.com/Minerx117/NemosMiner/blob/970abfce6bfeb34253a181c32a4cb628c3ab5ce5/Web/configedit.html

**Comment by UselessGuru** [comment]
@arminmacx 
Please close if you accept the fix.
