### ISSUE TITLE
5.0.0.2 not started mining

### ISSUE THREAD

**Issue by 9301039** [Minerx117/NemosMiner#97]
ERROR: Error in file Includes\Include.psm1 line 2071 detected. Restarting core

**Comment by 9301039** [comment]
![изображение](https://github.com/Minerx117/NemosMiner/assets/13090153/4c4a454d-8e78-4cb7-8dd9-08cc67fccb7c)

**Comment by UselessGuru** [comment]
Thank you for reporting. The error is [fixed in 5.0.0.3](https://github.com/Minerx117/NemosMiner/releases/tag/v5.0.0.3).
